import { UniverseJS } from './universe';

export interface Example {
  label: string;
  config: UniverseJS;
  description?: string;
}

export const EXAMPLES: Example[] = [
  {
    label: 'Waves',
    config: {
      selectedItems: [],
      controlsHidden: false,
      attractors: [
        {
          name: 'Attractor #0',
          label: 'Attractor #0',
          x: '250',
          y: '250',
          mass: 'sin(t / 50) * 20',
        },
      ],
      emitters: [
        {
          name: 'Emitter #0',
          label: 'Emitter #0',
          x: '50',
          y: '250',
          angle: '0',
          spread: 'pi / 4',
          velocity: '20',
          batchSize: '6',
          emissionRate: 't % 1 == 0',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #1',
          label: 'Emitter #1',
          x: '450',
          y: '250',
          angle: 'pi',
          spread: 'pi / 4',
          velocity: '20',
          batchSize: '6',
          emissionRate: 't % 1 == 0',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
      ],
    },
  },
  {
    label: 'Flower',
    config: {
      selectedItems: [],
      controlsHidden: false,
      attractors: [
        {
          name: 'Attractor #0',
          label: 'Attractor #0',
          x: '250',
          y: '250',
          mass: 'sin(t / 50) * 20',
        },
      ],
      emitters: [
        {
          name: 'Emitter #0',
          label: 'Emitter #0',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #1',
          label: 'Emitter #1',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #2',
          label: 'Emitter #2',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #3',
          label: 'Emitter #3',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },

        {
          name: 'Emitter #4',
          label: 'Emitter #4',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #5',
          label: 'Emitter #5',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #6',
          label: 'Emitter #6',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #7',
          label: 'Emitter #7',
          x: 'cos(t/100 + j*pi/(n/2))*200 + 250',
          y: '-sin(t/100 + j*pi/(n/2))*200 + 250',
          angle: '-t/100 + j*pi/(n/2) + (j +1) * pi',
          spread: 'pi / 4',
          velocity: '3',
          batchSize: '6',
          emissionRate: 'true',
          lifeSpan: '5000',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
      ],
    },
  },
  {
    label: 'Spiral',
    config: {
      selectedItems: [],
      controlsHidden: false,
      emitters: [
        {
          name: 'Emitter #2',
          label: 'Emitter #2',
          x: 'cos(t/100 + j*pi)*60 + 250',
          y: '-sin(t/100 + j*pi)*60 + 250',
          angle: '-t/100 + j*pi + pi + sin(t/100)',
          spread: 'pi / 4',
          velocity: '20',
          batchSize: '6',
          emissionRate: 't%2 == true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: 'Emitter #3',
          label: 'Emitter #3',
          x: 'cos(t/100 + j*pi)*60 + 250',
          y: '-sin(t/100 + j*pi)*60 + 250',
          angle: '-t/100 + j*pi + pi + sin(t/100)',
          spread: 'pi / 4',
          velocity: '20',
          batchSize: '6',
          emissionRate: 't%2 == true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
      ],
      attractors: [],
    },
  },
  {
    label: 'Small (200x200)',
    config: {
      selectedItems: [],
      controlsHidden: false,
      emitters: [0, 1, 2, 3, 4, 5, 6, 7].map(index => {
        const speed = 't/1000';

        return {
          name: `Emitter #${index}`,
          label: `Emitter #${index}`,
          x: `cos(${speed} + j*pi/(n/2))*60 + 100`,
          y: `-sin(${speed} + j*pi/(n/2))*60 + 100`,
          angle: `-${speed} + j*pi/(n/2) + (j +1) * pi + cos(${speed})*10`,
          spread: 'pi / 4',
          velocity: '20',
          batchSize: '12',
          emissionRate: 'true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        };
      }),
      attractors: [
        {
          name: 'Attractor #0',
          label: 'Attractor #0',
          x: '100',
          y: '100',
          mass: 'sin(t / 50) * 5',
        },
      ],
    },
  },
  {
    label: 'Corners (200x200)',
    config: {
      selectedItems: [],
      controlsHidden: false,
      emitters: [
        {
          name: `Emitter #0`,
          label: `Emitter #0`,
          x: '0',
          y: '0',
          angle: `pi / 4`,
          spread: 'pi / 4',
          velocity: '10',
          batchSize: '12',
          emissionRate: 'true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: `Emitter #1`,
          label: `Emitter #1`,
          x: '200',
          y: '0',
          angle: `-5pi / 4`,
          spread: '-pi / 4',
          velocity: '10',
          batchSize: '12',
          emissionRate: 'true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: `Emitter #2`,
          label: `Emitter #2`,
          x: '200',
          y: '200',
          angle: `-3pi / 4`,
          spread: '-pi / 4',
          velocity: '10',
          batchSize: '12',
          emissionRate: 'true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
        {
          name: `Emitter #3`,
          label: `Emitter #3`,
          x: '0',
          y: '200',
          angle: `-pi / 4`,
          spread: '-pi / 4',
          velocity: '10',
          batchSize: '12',
          emissionRate: 'true',
          lifeSpan: '500',
          hue: 'sin(t / 500) + 1',
          saturation: '.7',
          lightness: '.7',
        },
      ],

      attractors: [
        {
          name: 'Attractor #0',
          label: 'Attractor #0',
          x: '100',
          y: '100',
          mass: 'sin(t / 20) * 5',
        },
      ],
    },
  },
];
